# _config.yml
title: [GUIDE] Windows 11 Clean Install
description: A step-by-step guide to help you get a clean, nearly zero-bloat experience, on a fresh install of Windows 11.
markdown: kramdown
theme: just-the-docs
